### ISSUE TITLE
Type 'URL' is not assignable to type 'URL & Location

### ISSUE THREAD

**Issue by acrodrig** [aaronhuggins/deno_mocha#1]
I get the following error when I upgraded Deno (versions deno 1.13.2, v8 9.3.345.11, typescript 4.3.5):

```
error: TS2322 [ERROR]: Type 'URL' is not assignable to type 'URL & Location'.
  Type 'URL' is missing the following properties from type 'Location': ancestorOrigins, assign, reload, replace
  window.location = new URL('http://localhost:0')
```

Can you advise what the best workaround is? Or update the library? Thanks.

**Comment by ntrotner** [comment]
removing the line `window.location = new URL('http://localhost:0')` and using the `--location=http://localhost` flag helped me

**Comment by aaronhuggins** [comment]
I've completely changed direction on this library. It is no longer based on Mocha, in order to get Deno's built-in test harness features.
